const {expect}=require("chai");const {ethers}=require("hardhat");
describe("AtomicV4WethExecutor",function(){let owner,other,u,t,p2,swap,posm,ex,key,poolId,mintData,swapOpen,deadline;
beforeEach(async()=>{[owner,other]=await ethers.getSigners();const E=await ethers.getContractFactory("MockERC20");u=await E.deploy("WETH");t=await E.deploy("TOKEN");p2=await(await ethers.getContractFactory("MockPermit2")).deploy();swap=await(await ethers.getContractFactory("MockV4Swap")).deploy();posm=await(await ethers.getContractFactory("MockV4Posm")).deploy(p2.target);ex=await(await ethers.getContractFactory("AtomicV4WethExecutor")).deploy(owner.address,u.target,posm.target,p2.target,swap.target);await u.mint(owner.address,1000);await t.mint(owner.address,1000);await u.approve(ex.target,1000);await t.approve(ex.target,1000);const [c0,c1]=BigInt(u.target)<BigInt(t.target)?[u.target,t.target]:[t.target,u.target];key={currency0:c0,currency1:c1,fee:3000,tickSpacing:60,hooks:ethers.ZeroAddress};poolId=ethers.keccak256(ethers.AbiCoder.defaultAbiCoder().encode(["address","address","uint24","int24","address"],Object.values(key)));const amounts=c0===u.target?[60,40]:[40,60];const body=ethers.AbiCoder.defaultAbiCoder().encode(["tuple(address currency0,address currency1,uint24 fee,int24 tickSpacing,address hooks)","address","uint128","uint256","uint256"],[key,owner.address,100,...amounts]);mintData=posm.interface.encodeFunctionData("modifyLiquidities",[ethers.AbiCoder.defaultAbiCoder().encode(["uint8","bytes"],[1,body]),9999999999]);swapOpen=swap.interface.encodeFunctionData("swap",[u.target,t.target,40,39,ex.target]);await ex.setSwapSelector(swap.interface.getFunction("swap").selector,true);deadline=Number((await ethers.provider.getBlock("latest")).timestamp)+300;});
const ident=()=>({...key,poolId});const op=()=>({token:t.target,pool:ident(),wethAmount:100,swapAmount:40,minTokenOut:39,amount0Min:1,amount1Min:1,deadline,swapTarget:swap.target,swapData:swapOpen,mintData});
it("starts paused and atomically opens with executor sender/recipient",async()=>{expect(await ex.paused()).eq(true);await expect(ex.atomicOpen(op())).revertedWithCustomError(ex,"Paused");await ex.setPaused(false);await expect(ex.atomicOpen(op())).emit(ex,"Opened");expect(await posm.ownerOf(1)).eq(owner.address);expect(await u.balanceOf(ex.target)).eq(0);expect(await t.balanceOf(ex.target)).eq(0);});
it("inventory-opens exact caps, refunds dust, and revokes Permit2",async()=>{await ex.setPaused(false);const p={token:t.target,pool:ident(),wethAmount:70,tokenAmount:50,amount0Min:1,amount1Min:1,deadline,mintData};await expect(ex.atomicInventoryOpen(p)).emit(ex,"InventoryOpened");expect(await u.balanceOf(owner.address)).eq(940);expect(await t.balanceOf(owner.address)).eq(960);expect(await u.balanceOf(ex.target)).eq(0);expect(await t.balanceOf(ex.target)).eq(0);expect(await u.allowance(ex.target,p2.target)).eq(0);expect(await t.allowance(ex.target,p2.target)).eq(0);expect(await p2.a(ex.target,u.target,posm.target)).eq(0);expect(await p2.a(ex.target,t.target,posm.target)).eq(0);});
it("atomically removes and collects to owner before WETH settlement",async()=>{await ex.setPaused(false);await ex.atomicOpen(op());const body=ethers.AbiCoder.defaultAbiCoder().encode(["uint256","address"],[1,ex.target]);const closeData=posm.interface.encodeFunctionData("modifyLiquidities",[ethers.AbiCoder.defaultAbiCoder().encode(["uint8","bytes"],[2,body]),9999999999]);const swapData=swap.interface.encodeFunctionData("swap",[t.target,u.target,40,39,ex.target]);const p={tokenId:1,token:t.target,pool:ident(),liquidity:100,amount0Min:1,amount1Min:1,minSwapOut:39,minTotalWeth:99,deadline,swapTarget:swap.target,closeData,swapData};await swap.setFail(true);await expect(ex.atomicClose(p)).emit(ex,"Closed");expect(await u.balanceOf(owner.address)).eq(960);expect(await t.balanceOf(owner.address)).eq(1040);expect(await u.balanceOf(ex.target)).eq(0);expect(await t.balanceOf(ex.target)).eq(0);});
it("reverts atomically on downstream failure",async()=>{await ex.setPaused(false);await posm.setFail(true);await expect(ex.atomicOpen(op())).revertedWith("posm fail");expect(await u.balanceOf(owner.address)).eq(1000);expect(await u.balanceOf(ex.target)).eq(0);expect(await t.balanceOf(ex.target)).eq(0);});
it("rejects wrong target, selector, pool, owner and zero minima",async()=>{await ex.setPaused(false);await expect(ex.connect(other).atomicOpen(op())).revertedWithCustomError(ex,"Unauthorized");await expect(ex.atomicOpen({...op(),swapTarget:other.address})).revertedWithCustomError(ex,"TargetDenied");await expect(ex.atomicOpen({...op(),swapData:"0x12345678"})).revertedWithCustomError(ex,"SelectorDenied");await expect(ex.atomicOpen({...op(),minTokenOut:0})).revertedWithCustomError(ex,"Invalid");await expect(ex.atomicOpen({...op(),pool:{...ident(),fee:500}})).revertedWithCustomError(ex,"PoolMismatch");});});
