const {expect}=require("chai"); const {ethers}=require("hardhat");
describe("AtomicV3Executor contract",function(){let o,x,u,t,f,r,n,e,pool;const fee=500, A=1000n,S=400n;
async function deploy(){[o,x]=await ethers.getSigners();u=await ethers.deployContract("MockERC20",["USDG"]);t=await ethers.deployContract("MockERC20",["TOK"]);f=await ethers.deployContract("MockFactory");r=await ethers.deployContract("MockRouter");n=await ethers.deployContract("MockNPM");pool=x.address;let [a,b]=u.target.toLowerCase()<t.target.toLowerCase()?[u.target,t.target]:[t.target,u.target];await f.set(a,b,fee,pool);e=await ethers.deployContract("AtomicV3Executor",[o.address,u.target,f.target,n.target,r.target,r.target]);await u.mint(o.address,100000n);await u.approve(e.target,100000n);await t.mint(r.target,100000n);await e.setSwapSelector(r.interface.getFunction("aggregate").selector,true);}
async function dl(d=100){return BigInt((await ethers.provider.getBlock("latest")).timestamp+d)}
async function op(ch={}){return {token:t.target,expectedPool:pool,fee,tickLower:-10,tickUpper:10,usdgAmount:A,swapAmount:S,minTokenOut:1n,amount0Min:0,amount1Min:0,deadline:await dl(),sqrtPriceLimitX96:0,...ch}}
async function open(ch={}){await e.setPaused(false);return e.atomicOpen(await op(ch))}
async function cp(ch={}){let P=await n.ps(1),td=P.t0.toLowerCase()===t.target.toLowerCase()?P.liq/2n:P.liq-P.liq/2n;let swapData=r.interface.encodeFunctionData("aggregate",[t.target,u.target,e.target,e.target,td,1]);return {tokenId:1,token:t.target,expectedPool:pool,fee,tickLower:-10,tickUpper:10,liquidity:P.liq,amount0Min:0,amount1Min:0,minSwapOut:1,minTotalUsdg:1,deadline:await dl(),swapTarget:r.target,swapData,burn:false,...ch}}
beforeEach(deploy);
it("starts paused and owner-only",async()=>{expect(await e.paused()).eq(true);await expect(e.atomicOpen(await op())).revertedWithCustomError(e,"Paused");await expect(e.connect(x).setPaused(false)).revertedWithCustomError(e,"Unauthorized")});
it("opens end-to-end, exact pull, wallet NFT, refunds dust",async()=>{let b=await u.balanceOf(o);await open();expect(b-await u.balanceOf(o)).eq(A-1n);expect((await n.ps(1)).owner).eq(o.address);expect(await u.balanceOf(e.target)).eq(0);expect(await t.balanceOf(e.target)).eq(0)});
it("rejects zero, expired and far deadlines",async()=>{await e.setPaused(false);await expect(e.atomicOpen(await op({deadline:0}))).revertedWithCustomError(e,"Expired");await expect(e.atomicOpen(await op({deadline:1}))).revertedWithCustomError(e,"Expired");await expect(e.atomicOpen(await op({deadline:await dl(1900)}))).revertedWithCustomError(e,"DeadlineTooFar")});
it("requires nonzero minOut and valid amounts",async()=>{await e.setPaused(false);await expect(e.atomicOpen(await op({minTokenOut:0}))).revertedWithCustomError(e,"Invalid");await expect(e.atomicOpen(await op({swapAmount:A}))).revertedWithCustomError(e,"Invalid")});
it("validates factory pool identity",async()=>{await e.setPaused(false);await expect(e.atomicOpen(await op({expectedPool:o.address}))).revertedWithCustomError(e,"PoolMismatch")});
it("rejects dirty USDG/token balances",async()=>{await u.mint(e.target,1);await e.setPaused(false);await expect(e.atomicOpen(await op())).revertedWithCustomError(e,"DirtyBalance")});
it("swap revert atomically rolls back pull",async()=>{await r.setFail(true);let b=await u.balanceOf(o);await expect(open()).revertedWith("swap fail");expect(await u.balanceOf(o)).eq(b);expect(await u.balanceOf(e.target)).eq(0)});
it("mint revert atomically rolls back swap and pull",async()=>{await n.setFailMint(true);let b=await u.balanceOf(o);await expect(open()).revertedWith("mint fail");expect(await u.balanceOf(o)).eq(b);expect(await u.balanceOf(e.target)).eq(0);expect(await t.balanceOf(e.target)).eq(0)});
it("fee-on-transfer USDG fails exact-pull closed",async()=>{await u.setFee(100);await expect(open()).revertedWithCustomError(e,"PullFailed");expect(await u.balanceOf(e.target)).eq(0)});
it("settles principal atomically but leaves zero-liquidity NFT",async()=>{await open();await n.setApprovalForAll(e.target,true);let b=await u.balanceOf(o);await e.atomicClose(await cp());expect(await u.balanceOf(o)).gt(b);expect((await n.ps(1)).owner).eq(o.address);expect((await n.ps(1)).liq).eq(0);expect(await u.balanceOf(e.target)).eq(0);expect(await t.balanceOf(e.target)).eq(0)});
it("collects principal plus accrued fees and attributes exact owner deltas",async()=>{await open();await n.setApprovalForAll(e.target,true);let P=await n.ps(1),u0=P.t0.toLowerCase()===u.target.toLowerCase();await n.addFees(1,u0?7:11,u0?11:7);let ub=await u.balanceOf(o),tb=await t.balanceOf(o);await e.atomicClose(await cp());P=await n.ps(1);expect(P.owed0).eq(0);expect(P.owed1).eq(0);expect(await u.balanceOf(o)).gt(ub);expect(await t.balanceOf(o)).gt(tb);expect(P.liq).eq(0)});
it("rejects atomic burn so residual fees cannot be accidentally collected",async()=>{await open();await n.setApprovalForAll(e.target,true);await expect(e.atomicClose(await cp({burn:true}))).revertedWithCustomError(e,"Invalid")});
it("close without NFT operator approval fails",async()=>{await open();await expect(e.atomicClose(await cp())).revertedWith("nft approval")});
it("close performs no router call",async()=>{await open();await n.setApprovalForAll(e.target,true);await r.setFail(true);await expect(e.atomicClose(await cp())).emit(e,"Closed");expect((await n.ps(1)).liq).eq(0)});
it("close validates NFT identity and liquidity",async()=>{await open();await n.setApprovalForAll(e.target,true);await expect(e.atomicClose(await cp({tickLower:-9}))).revertedWithCustomError(e,"PoolMismatch");await expect(e.atomicClose(await cp({liquidity:(await n.ps(1)).liq+1n}))).revertedWithCustomError(e,"PoolMismatch")});
it("legacy swap floors cannot influence remove and collect",async()=>{await open();await n.setApprovalForAll(e.target,true);await expect(e.atomicClose(await cp({minTotalUsdg:999999n,minSwapOut:999999n}))).emit(e,"Closed")});
it("close rejects preexisting executor balances",async()=>{await open();await n.setApprovalForAll(e.target,true);await t.mint(e.target,1);await expect(e.atomicClose(await cp())).revertedWithCustomError(e,"DirtyBalance")});
it("close ignores aggregator fields and never calls their target",async()=>{await open();await n.setApprovalForAll(e.target,true);await expect(e.atomicClose(await cp({swapTarget:x.address,swapData:"0x12345678"}))).emit(e,"Closed")});
it("pause blocks both lifecycle operations",async()=>{await e.setPaused(false);await e.setPaused(true);await expect(e.atomicOpen(await op())).revertedWithCustomError(e,"Paused")});
it("two-step ownership transfer",async()=>{await e.transferOwnership(x.address);await expect(e.connect(o).acceptOwnership()).revertedWithCustomError(e,"Unauthorized");await e.connect(x).acceptOwnership();expect(await e.owner()).eq(x.address);await expect(e.setPaused(false)).revertedWithCustomError(e,"Unauthorized")});
it("rescue is owner-only and paused-only",async()=>{await t.mint(e.target,7);await expect(e.connect(x).rescue(t.target)).revertedWithCustomError(e,"Unauthorized");await e.setPaused(false);await expect(e.rescue(t.target)).revertedWithCustomError(e,"Invalid");await e.setPaused(true);let b=await t.balanceOf(o);await e.rescue(t.target);expect(await t.balanceOf(o)).eq(b+7n)});
it("chain guard constant/local chain configured",async()=>{expect((await ethers.provider.getNetwork()).chainId).eq(4663n);expect(await e.CHAIN_ID()).eq(4663n)});
});
