#!/usr/bin/env node
/** AtomicV4Executor sidecar. Only execute-close signs, and it broadcasts one atomicClose tx. */
import fs from "node:fs";
import { ethers } from "ethers";
import { provider, wallet } from "./chain/client.js";
import { C, cfg, env } from "./config.js";
import { kyberBuild, kyberRoute } from "./chain/kyber.js";
import { generateOpenPlan, generateInventoryOpenPlan, generateClosePlan } from "./atomic-v4-plan.js";
const OWNER="0x3582605Edebf376b684a45E8Faa6D808C22a8e3e";
const USDG="0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168";
const ABI=["function owner() view returns(address)","function paused() view returns(bool)","function USDG() view returns(address)","function POSITION_MANAGER() view returns(address)","function SWAP_TARGET() view returns(address)","function swapSelectorAllowed(bytes4) view returns(bool)","function atomicOpen((address token,(address currency0,address currency1,uint24 fee,int24 tickSpacing,address hooks,bytes32 poolId) pool,uint256 usdgAmount,uint256 swapAmount,uint256 minTokenOut,uint256 amount0Min,uint256 amount1Min,uint256 deadline,address swapTarget,bytes swapData,bytes mintData)) returns(uint256)","function atomicInventoryOpen((address token,(address currency0,address currency1,uint24 fee,int24 tickSpacing,address hooks,bytes32 poolId) pool,uint256 usdgAmount,uint256 tokenAmount,uint256 amount0Min,uint256 amount1Min,uint256 deadline,bytes mintData)) returns(uint256)","function atomicClose((uint256 tokenId,address token,(address currency0,address currency1,uint24 fee,int24 tickSpacing,address hooks,bytes32 poolId) pool,uint128 liquidity,uint256 amount0Min,uint256 amount1Min,uint256 minSwapOut,uint256 minTotalUsdg,uint256 deadline,address swapTarget,bytes closeData,bytes swapData)) returns(uint256)"];
const MOD=new ethers.Interface(["function modifyLiquidities(bytes,uint256)"]).getFunction("modifyLiquidities")!.selector;
const CLOSED=new ethers.Interface(["event Closed(uint256 indexed tokenId,address indexed token,uint256 settlementAmount,uint256 tokenAmount)"]);
const OPENED=new ethers.Interface(["event Opened(uint256 indexed tokenId,address indexed token,bytes32 indexed poolId,uint256 usdgIn,uint256 tokenOut)"]);
const POS=["function ownerOf(uint256) view returns(address)","function getPositionLiquidity(uint256) view returns(uint128)"];
const ERC20=["function balanceOf(address) view returns(uint256)"];
const json=(x:unknown)=>console.log(JSON.stringify(x,(_k,v)=>typeof v==="bigint"?v.toString():v));
function positive(p:any,names:string[]){for(const n of names)if(BigInt(p[n]??0)<=0n)throw Error(`${n} must be nonzero`);}
function pool(p:any){const id=ethers.keccak256(ethers.AbiCoder.defaultAbiCoder().encode(["address","address","uint24","int24","address"],[p.currency0,p.currency1,p.fee,p.tickSpacing,p.hooks]));if(id.toLowerCase()!==String(p.poolId).toLowerCase())throw Error("poolId identity mismatch");if(![p.currency0.toLowerCase(),p.currency1.toLowerCase()].includes(USDG.toLowerCase()))throw Error("pool is not USDG paired");}
async function identity(addr:string){if((await provider.getNetwork()).chainId!==4663n||cfg.chainId!==4663)throw Error("wrong chain");const e=new ethers.Contract(addr,ABI,provider);const [o,u,p,s,paused]=await Promise.all([e.owner(),e.USDG(),e.POSITION_MANAGER(),e.SWAP_TARGET(),e.paused()]);if(ethers.getAddress(o)!==OWNER||ethers.getAddress(u)!==USDG||ethers.getAddress(p)!==ethers.getAddress(C.v4PositionManager!)||ethers.getAddress(s)!==ethers.getAddress(env.kyberRouter))throw Error("executor chain/owner/contract identity mismatch");return {e,paused,swapTarget:s};}
async function dry(kind:"open"|"close",file:string){const addr=process.env.ATOMIC_V4_EXECUTOR_ADDRESS;if(!addr)throw Error("ATOMIC_V4_EXECUTOR_ADDRESS required");const p=JSON.parse(fs.readFileSync(file,"utf8"));pool(p.pool);positive(p,kind==="open"?["usdgAmount","swapAmount","minTokenOut","amount0Min","amount1Min"]:["liquidity","amount0Min","amount1Min"]);if(kind==="open"&&BigInt(p.swapAmount)>=BigInt(p.usdgAmount))throw Error("swapAmount must be below budget");const {e,paused,swapTarget}=await identity(addr);if(ethers.getAddress(p.swapTarget)!==ethers.getAddress(swapTarget))throw Error("swap target not allowlisted");const sel=String(p.swapData).slice(0,10), allowed=await e.swapSelectorAllowed(sel);if(!allowed)throw Error(`swap selector ${sel} not allowlisted`);const lifecycle=kind==="open"?p.mintData:p.closeData;if(String(lifecycle).slice(0,10)!==MOD)throw Error("PositionManager selector denied");const fn=kind==="open"?"atomicOpen":"atomicClose",data=e.interface.encodeFunctionData(fn,[p]);let simulation:any={ok:false};try{const result=await provider.call({from:OWNER,to:addr,data});const gas=await provider.estimateGas({from:OWNER,to:addr,data});simulation={ok:true,result,gas};}catch(err:any){simulation={ok:false,expectedPaused:Boolean(paused),error:String(err.shortMessage||err.message).slice(0,300)};if(!paused)throw Error(`eth_call reverted: ${simulation.error}`);}return {safeDryRun:true,broadcast:false,chainId:4663,executor:addr,owner:OWNER,paused,operation:kind,selector:sel,calldata:data,simulation};}
async function swapBuild(tokenIn:string,tokenOut:string,raw:string){const addr=process.env.ATOMIC_V4_EXECUTOR_ADDRESS;if(!addr)throw Error("ATOMIC_V4_EXECUTOR_ADDRESS required");const amount=BigInt(raw);if(amount<=0n)throw Error("amount must be positive");const {e,swapTarget}=await identity(addr),route=await kyberRoute(tokenIn,tokenOut,amount);if(!route)throw Error("no Kyber route");const b=await kyberBuild(route.routeSummary,addr,addr,Math.round((cfg.lp.slippagePct||5)*100));if(!b)throw Error("Kyber build unavailable");if(ethers.getAddress(b.routerAddress)!==ethers.getAddress(swapTarget))throw Error("Kyber target mismatch");if(BigInt(b.amountIn)!==amount||BigInt(b.amountOut)<=0n)throw Error("Kyber amount integrity failed");const selector=String(b.data).slice(0,10);if(!await e.swapSelectorAllowed(selector))throw Error(`swap selector ${selector} not allowlisted`);return {safeDryRun:true,broadcast:false,sender:addr,recipient:addr,target:swapTarget,selector,amountIn:b.amountIn,quotedOut:route.routeSummary.amountOut,builtOut:b.amountOut,value:b.transactionValue??"0",calldata:b.data};}
async function executeClose(tokenId:string){
 const addr=process.env.ATOMIC_V4_EXECUTOR_ADDRESS||"0xF8b9C6A7453a52A3F515824939a3c69292f81921", tmp=`/tmp/atomic-v4-close-${process.pid}-${tokenId}.json`;
 try {
  const p=await generateClosePlan(tokenId,tmp,Number(process.env.ATOMIC_V4_SLIPPAGE_BPS||"500"));pool(p.pool);positive(p,["liquidity","amount0Min","amount1Min"]);
  const {e,paused}=await identity(addr);if(paused)throw Error("executor paused");const data=e.interface.encodeFunctionData("atomicClose",[p]);
  await provider.call({from:OWNER,to:addr,data});const estimate=await provider.estimateGas({from:OWNER,to:addr,data}),gasCap=BigInt(process.env.ATOMIC_V4_GAS_LIMIT_CAP||"2000000");if(estimate>gasCap)throw Error(`gas estimate ${estimate} exceeds cap ${gasCap}`);
  const fees=await provider.getFeeData(),maxFee=fees.maxFeePerGas??fees.gasPrice;if(!maxFee||maxFee>ethers.parseUnits(process.env.ATOMIC_V4_MAX_GAS_GWEI||"5","gwei"))throw Error("gas fee unavailable or above cap");
  const w=wallet();if(ethers.getAddress(w.address)!==OWNER)throw Error("wallet identity mismatch");const [nonce,latest]=await Promise.all([provider.getTransactionCount(OWNER,"pending"),provider.getTransactionCount(OWNER,"latest")]);if(nonce!==latest)throw Error("pending nonce exists");
  // Exactly one signing/broadcast call; approvals and compensating transactions are forbidden here.
  const tx=await w.sendTransaction({to:addr,data,nonce,gasLimit:estimate*120n/100n,maxFeePerGas:maxFee,maxPriorityFeePerGas:fees.maxPriorityFeePerGas??0n}),r=await tx.wait();if(!r||r.status!==1)throw Error("atomicClose receipt failed");
  const events=r.logs.flatMap((l:any)=>{try{const x=CLOSED.parseLog(l);return x?.name==="Closed"?[x]:[]}catch{return []}});if(events.length!==1||events[0].args.tokenId!==BigInt(tokenId)||ethers.getAddress(events[0].args.token)!==ethers.getAddress(p.token))throw Error("unique matching Closed event missing");
  const [u,t]=await Promise.all([new ethers.Contract(USDG,ERC20,provider).balanceOf(addr),new ethers.Contract(p.token,ERC20,provider).balanceOf(addr)]);if(u!==0n||t!==0n)throw Error(`executor residual balance usdg=${u} token=${t}`);
  return {receipt:{hash:r.hash,status:r.status,blockNumber:r.blockNumber,gasUsed:r.gasUsed,nonce},event:{name:"Closed",tokenId,token:p.token,settlementAmount:events[0].args.settlementAmount,tokenAmount:events[0].args.tokenAmount},nftGone:true,removeCollectConfirmed:true,settlementComplete:events[0].args.tokenAmount===0n,totalUsdgProceedsRaw:events[0].args.settlementAmount,sourceTokenDeltaRaw:events[0].args.tokenAmount,executorBalances:{usdg:u,token:t}};
 } finally {try{fs.unlinkSync(tmp)}catch{}}
}
async function executeOpen(token:string,budget:string,poolId?:string){
 const addr=process.env.ATOMIC_V4_EXECUTOR_ADDRESS||"0xF8b9C6A7453a52A3F515824939a3c69292f81921",tmp=`/tmp/atomic-v4-open-${process.pid}.json`;
 try {
  const p=await generateOpenPlan(token,BigInt(budget),tmp,Number(process.env.ATOMIC_V4_SLIPPAGE_BPS||"500"),8,poolId);pool(p.pool);positive(p,["usdgAmount","swapAmount","minTokenOut","amount0Min","amount1Min"]);
  const {e,paused}=await identity(addr);if(paused)throw Error("executor paused");const data=e.interface.encodeFunctionData("atomicOpen",[p]);await provider.call({from:OWNER,to:addr,data});
  const estimate=await provider.estimateGas({from:OWNER,to:addr,data}),cap=BigInt(process.env.ATOMIC_V4_GAS_LIMIT_CAP||"2000000");if(estimate>cap)throw Error(`gas estimate ${estimate} exceeds cap ${cap}`);
  const fees=await provider.getFeeData(),maxFee=fees.maxFeePerGas??fees.gasPrice;if(!maxFee||maxFee>ethers.parseUnits(process.env.ATOMIC_V4_MAX_GAS_GWEI||"5","gwei"))throw Error("gas fee unavailable or above cap");
  const w=wallet();if(ethers.getAddress(w.address)!==OWNER)throw Error("wallet identity mismatch");const [nonce,latest]=await Promise.all([provider.getTransactionCount(OWNER,"pending"),provider.getTransactionCount(OWNER,"latest")]);if(nonce!==latest)throw Error("pending nonce exists");
  const tx=await w.sendTransaction({to:addr,data,nonce,gasLimit:estimate*120n/100n,maxFeePerGas:maxFee,maxPriorityFeePerGas:fees.maxPriorityFeePerGas??0n}),r=await tx.wait();if(!r||r.status!==1)throw Error("atomicOpen receipt failed");
  const events=r.logs.flatMap((l:any)=>{try{const x=OPENED.parseLog(l);return x?.name==="Opened"?[x]:[]}catch{return []}});if(events.length!==1)throw Error("unique Opened event missing");const ev=events[0],tokenId=ev.args.tokenId;if(ethers.getAddress(ev.args.token)!==ethers.getAddress(p.token)||String(ev.args.poolId).toLowerCase()!==p.pool.poolId.toLowerCase())throw Error("Opened event mismatch");
  const pm=new ethers.Contract(C.v4PositionManager!,POS,provider),[owner,liq,u,t]=await Promise.all([pm.ownerOf(tokenId),pm.getPositionLiquidity(tokenId),new ethers.Contract(USDG,ERC20,provider).balanceOf(addr),new ethers.Contract(p.token,ERC20,provider).balanceOf(addr)]);if(ethers.getAddress(owner)!==OWNER||liq<=0n)throw Error("minted NFT verification failed");if(u!==0n||t!==0n)throw Error(`executor residual balance usdg=${u} token=${t}`);
  return {receipt:{hash:r.hash,status:r.status,blockNumber:r.blockNumber,gasUsed:r.gasUsed,nonce},event:{name:"Opened",tokenId:String(tokenId),token:p.token,poolId:p.pool.poolId,usdgIn:ev.args.usdgIn,tokenOut:ev.args.tokenOut},tokenId:String(tokenId),poolId:p.pool.poolId,tickLower:p.meta.tickLower,tickUpper:p.meta.tickUpper,txHash:r.hash,swapHash:r.hash,nftOwner:owner,liquidity:liq,executorBalances:{usdg:u,token:t}};
 } finally {try{fs.unlinkSync(tmp)}catch{}}
}
async function main(){const [cmd,a,b,c,d,e]=process.argv.slice(2);if(cmd==="execute-open"&&a&&b)return json({ok:true,result:await executeOpen(a,b,c)});if(cmd==="execute-close"&&a)return json({ok:true,result:await executeClose(a)});if(cmd==="build-swap"&&a&&b&&c)return json({ok:true,result:await swapBuild(a,b,c)});if(cmd==="generate-open"&&a&&b&&c)return json({ok:true,result:await generateOpenPlan(a,BigInt(b),c,d?Number(d):500,8,e)});if(cmd==="generate-inventory-open"&&a)return json({ok:true,result:await generateInventoryOpenPlan(a,b?Number(b):500,c?Number(c):8)});if(cmd==="generate-close"&&a&&b)return json({ok:true,result:await generateClosePlan(a,b,c?Number(c):500)});if(cmd==="dry-open"&&a)return json({ok:true,result:await dry("open",a)});if(cmd==="dry-close"&&a)return json({ok:true,result:await dry("close",a)});throw Error("commands: execute-close TOKEN_ID | generate-open BUDGET_RAW OUT.json [SLIPPAGE_BPS] | generate-inventory-open OUT.json [SLIPPAGE_BPS] [WIDTH_SPACINGS] | generate-close TOKEN_ID OUT.json [SLIPPAGE_BPS] | build-swap TOKEN_IN TOKEN_OUT AMOUNT_RAW | dry-open PLAN.json | dry-close PLAN.json");}
main().catch(e=>{console.error(JSON.stringify({ok:false,error:String(e.message||e).slice(0,500)}));process.exit(1)});
