#!/usr/bin/env node
/** AtomicV3Executor JSON sidecar. Build commands never sign; execute commands rebuild,
 * simulate and estimate immediately before signing exactly one lifecycle transaction. */
import { ethers } from "ethers";
import sdkCore from "@uniswap/sdk-core";
import v3sdk from "@uniswap/v3-sdk";
import JSBI from "jsbi";
import { provider, wallet } from "./chain/client.js";
import { cfg, C, env } from "./config.js";
import { kyberBuild, kyberRoute } from "./chain/kyber.js";
import { expectedMintAmounts } from "./chain/atomic-math.js";
const {Token}=sdkCore as any, {Pool,Position,TickMath,nearestUsableTick}=v3sdk as any;
const EXEC=process.env.ATOMIC_EXECUTOR_ADDRESS||"0xdfdb577269648B5d2F5aE1d87c08883b92696088";
const USDG="0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168", OWNER="0x3582605Edebf376b684a45E8Faa6D808C22a8e3e";
const ABI=["function owner() view returns(address)","function paused() view returns(bool)","function USDG() view returns(address)","function POSITION_MANAGER() view returns(address)","function SWAP_TARGET() view returns(address)","function CLOSE_MODE() view returns(bytes32)","function swapSelectorAllowed(bytes4) view returns(bool)","function atomicOpen((address token,address expectedPool,uint24 fee,int24 tickLower,int24 tickUpper,uint256 usdgAmount,uint256 swapAmount,uint256 minTokenOut,uint256 amount0Min,uint256 amount1Min,uint256 deadline,uint160 sqrtPriceLimitX96)) returns(uint256)","function atomicClose((uint256 tokenId,address token,address expectedPool,uint24 fee,int24 tickLower,int24 tickUpper,uint128 liquidity,uint256 amount0Min,uint256 amount1Min,uint256 minSwapOut,uint256 minTotalUsdg,uint256 deadline,address swapTarget,bytes swapData,bool burn)) returns(uint256)","function setPaused(bool)","event Opened(uint256 indexed tokenId,address indexed token,address pool,uint256 usdgIn,uint256 tokenOut)","event Closed(uint256 indexed tokenId,address indexed token,uint256 settlementAmount,uint256 tokenAmount)"];
const FACT=["function getPool(address,address,uint24) view returns(address)"];
const POOL=["function slot0() view returns(uint160,int24,uint16,uint16,uint16,uint8,bool)","function liquidity() view returns(uint128)","function tickSpacing() view returns(int24)"];
const NPM=["function positions(uint256) view returns(uint96,address,address,address,uint24,int24,int24,uint128,uint256,uint256,uint128,uint128)","function isApprovedForAll(address,address) view returns(bool)","function setApprovalForAll(address,bool)"];
const ERC=["function decimals() view returns(uint8)","function balanceOf(address) view returns(uint256)","function allowance(address,address) view returns(uint256)","function approve(address,uint256) returns(bool)"];
const QUOTER=["function quoteExactInputSingle((address tokenIn,address tokenOut,uint256 amountIn,uint24 fee,uint160 sqrtPriceLimitX96)) returns(uint256 amountOut,uint160,uint32,uint256)"];
const json=(x:any)=>console.log(JSON.stringify(x,(_k,v)=>typeof v==="bigint"?v.toString():v));
const slip=()=>BigInt(Math.round((100-Number(process.env.ATOMIC_SLIPPAGE_PCT||"3"))*100));
const min=(x:bigint)=>x*slip()/10000n;
async function poolFor(token:string){for(const fee of cfg.lp.feeTiers){const p=await new ethers.Contract(C.factory,FACT,provider).getPool(USDG,token,fee);if(p!==ethers.ZeroAddress){const pc=new ethers.Contract(p,POOL,provider);if(await pc.liquidity()>0n)return {pool:p,fee,pc};}}throw Error("no active direct USDG V3 pool");}
async function quote(a:string,b:string,n:bigint,fee:number){const q=new ethers.Contract(C.quoter,QUOTER,provider);const r=await q.quoteExactInputSingle.staticCall({tokenIn:a,tokenOut:b,amountIn:n,fee,sqrtPriceLimitX96:0});if(r[0]<=0n)throw Error("zero quote / FOT or hooked token unsupported");return {amountOut:r[0] as bigint,sqrtPriceX96After:r[1] as bigint};}

async function simulate(data:string){const code=(await provider.getCode(EXEC)).toLowerCase();const router02Selector=ethers.id("exactInputSingle((address,address,uint24,address,uint256,uint256,uint160))").slice(2,10);const legacySelector=ethers.id("exactInputSingle((address,address,uint24,address,uint256,uint256,uint256,uint160))").slice(2,10);if(!code.includes(router02Selector))throw Error(`executor bytecode is incompatible with SwapRouter02${code.includes(legacySelector)?" (legacy deadline-bearing exactInputSingle ABI)":""}; deploy the current AtomicV3Executor`);const tx={from:OWNER,to:EXEC,data};if(process.env.ATOMIC_DEBUG_DATA==='1')console.error(JSON.stringify({debugData:data}));await provider.call(tx);const gas=await provider.estimateGas(tx);const cap=BigInt(process.env.ATOMIC_GAS_LIMIT_CAP||"1500000");if(gas>cap)throw Error(`gas estimate ${gas} exceeds cap ${cap}`);return gas;}
async function requireRemoveCollectExecutor(){const e=new ethers.Contract(EXEC,ABI,provider),expected=ethers.id("REMOVE_COLLECT_ONLY_V1");let mode:string;try{mode=await e.CLOSE_MODE();}catch{throw Error("executor is not the remove+collect-only AtomicV3Executor; deploy the current matching executor");}if(mode!==expected)throw Error("executor close mode mismatch; deploy the current matching executor");}

async function open(token:string,raw:string){token=ethers.getAddress(token);let amount=BigInt(raw),cap=BigInt(process.env.ATOMIC_MAX_USDG_RAW||"250000000");if(amount<=0n||amount>cap)throw Error("USDG amount outside configured cap");const {pool,fee,pc}=await poolFor(token);const [s0,spacing,liq,tokenDecimals]=await Promise.all([pc.slot0(),pc.tickSpacing(),pc.liquidity(),new ethers.Contract(token,ERC,provider).decimals()]);const width=Math.max(1,Math.floor(Number(process.env.ATOMIC_RANGE_PCT||"20")*100));const dt=Math.floor(Math.log(1+width/10000)/Math.log(1.0001));let lo=nearestUsableTick(Number(s0[1])-dt,Number(spacing)),hi=nearestUsableTick(Number(s0[1])+dt,Number(spacing));if(lo>=hi)throw Error("invalid range");const swap=amount/2n,q=await quote(USDG,token,swap,fee),out=q.amountOut;/* Mandatory expected-size sellability proof. Hooked/FOT tokens that cannot execute through the executor-compatible V3 route fail here. */const reverse=await quote(token,USDG,out,fee);if(reverse.amountOut<=0n)throw Error("reverse sellability proof failed");const deadline=Math.floor(Date.now()/1000)+Math.min(600,Number(process.env.ATOMIC_DEADLINE_SECONDS||"300"));const usdg0=USDG.toLowerCase()<token.toLowerCase();const token0=new Token(4663,usdg0?USDG:token,usdg0?6:Number(tokenDecimals)),token1=new Token(4663,usdg0?token:USDG,usdg0?Number(tokenDecimals):6);const tickAfter=Number(TickMath.getTickAtSqrtRatio(JSBI.BigInt(q.sqrtPriceX96After.toString())).toString());const postSwapPool=new Pool(token0,token1,fee,q.sqrtPriceX96After.toString(),liq.toString(),tickAfter);const desired0=usdg0?amount-swap:out,desired1=usdg0?out:amount-swap;const expected=expectedMintAmounts(postSwapPool,lo,hi,desired0,desired1);if(expected.amount0<=0n||expected.amount1<=0n)throw Error("range would mint zero of one token at post-swap price");const p={token,expectedPool:pool,fee,tickLower:lo,tickUpper:hi,usdgAmount:amount,swapAmount:swap,minTokenOut:min(out),amount0Min:min(expected.amount0),amount1Min:min(expected.amount1),deadline,sqrtPriceLimitX96:0};if(p.amount0Min<=0n||p.amount1Min<=0n)throw Error("mint minima round to zero");const c=new ethers.Contract(EXEC,ABI,provider),data=c.interface.encodeFunctionData("atomicOpen",[p]);if(process.env.ATOMIC_DEBUG)console.error(JSON.stringify({p,desired0,desired1,expected},(_k,v)=>typeof v==="bigint"?v.toString():v));return {operation:"open",params:p,quote:{tokenOut:out,sqrtPriceX96After:q.sqrtPriceX96After,expectedMintAmount0:expected.amount0,expectedMintAmount1:expected.amount1},transaction:{to:EXEC,data,gasLimit:await simulate(data)}};}
async function close(id:string){const npm=new ethers.Contract(C.positionManager,NPM,provider),v=await npm.positions(id);if(v[7]===0n)throw Error("position has zero liquidity");const token=(v[2].toLowerCase()===USDG.toLowerCase()?v[3]:v[2]) as string;if(v[2].toLowerCase()!==USDG.toLowerCase()&&v[3].toLowerCase()!==USDG.toLowerCase())throw Error("NFT is not direct USDG/token");const pool=await new ethers.Contract(C.factory,FACT,provider).getPool(v[2],v[3],v[4]);const pc=new ethers.Contract(pool,POOL,provider),[s0,liq,dec]=await Promise.all([pc.slot0(),pc.liquidity(),new ethers.Contract(token,ERC,provider).decimals()]);const P=new Pool(new Token(4663,v[2],v[2].toLowerCase()===USDG.toLowerCase()?6:Number(dec)),new Token(4663,v[3],v[3].toLowerCase()===USDG.toLowerCase()?6:Number(dec)),Number(v[4]),s0[0].toString(),liq.toString(),Number(s0[1]));const pos=new Position({pool:P,liquidity:v[7].toString(),tickLower:Number(v[5]),tickUpper:Number(v[6])});const principal0=BigInt(pos.amount0.quotient.toString()),principal1=BigInt(pos.amount1.quotient.toString());// Atomic close settles only principal. positions().tokensOwed are fees and must
// remain in the zero-liquidity NFT for the separately journaled fee close.
const a0=principal0,a1=principal1;await requireRemoveCollectExecutor();const deadline=Math.floor(Date.now()/1000)+Math.min(600,Number(process.env.ATOMIC_DEADLINE_SECONDS||"300"));const p={tokenId:BigInt(id),token,expectedPool:pool,fee:Number(v[4]),tickLower:Number(v[5]),tickUpper:Number(v[6]),liquidity:v[7],amount0Min:min(principal0),amount1Min:min(principal1),minSwapOut:0n,minTotalUsdg:0n,deadline,swapTarget:ethers.ZeroAddress,swapData:"0x",burn:false};const c=new ethers.Contract(EXEC,ABI,provider),data=c.interface.encodeFunctionData("atomicClose",[p]);return {operation:"close",params:p,expectedPrincipal:{amount0:a0,amount1:a1},transaction:{to:EXEC,data,gasLimit:await simulate(data)}};}
async function liquidation(token:string,raw:string,minRaw:string){token=ethers.getAddress(token);const amount=BigInt(raw),minimum=BigInt(minRaw);if(amount<=0n||minimum<=0n)throw Error("invalid liquidation amount/minOut");const route=await kyberRoute(token,USDG,amount);if(!route)throw Error("no Kyber liquidation route");const bps=Math.round((cfg.lp.slippagePct||5)*100);if(bps<=0||bps>1000)throw Error("slippage exceeds hard 10% liquidation cap");const built=await kyberBuild(route.routeSummary,OWNER,OWNER,bps);if(!built)throw Error("Kyber liquidation build unavailable");if(ethers.getAddress(built.routerAddress)!==ethers.getAddress(env.kyberRouter)||BigInt(built.transactionValue||"0")!==0n||BigInt(built.amountIn)!==amount||BigInt(built.amountOut)<minimum)throw Error("unsafe Kyber liquidation build");return {operation:"liquidation",amountIn:amount,minOut:minimum,transaction:{to:env.kyberRouter,data:built.data,value:0n}};}
async function executeLiquidation(token:string,raw:string,minRaw:string){const w=wallet(),amount=BigInt(raw),erc=new ethers.Contract(token,ERC,w);if(w.address.toLowerCase()!==OWNER.toLowerCase())throw Error("wallet identity mismatch");let pending=await provider.getTransactionCount(OWNER,"pending"),latest=await provider.getTransactionCount(OWNER,"latest");if(pending!==latest)throw Error("pending nonce exists");if(await erc.allowance(OWNER,env.kyberRouter)<amount){const a=await erc.approve(env.kyberRouter,amount);const ar=await a.wait();if(!ar||ar.status!==1)throw Error("Kyber approval failed");}const b=await liquidation(token,raw,minRaw);await provider.call({from:OWNER,...b.transaction});const gas=await provider.estimateGas({from:OWNER,...b.transaction});pending=await provider.getTransactionCount(OWNER,"pending");latest=await provider.getTransactionCount(OWNER,"latest");if(pending!==latest)throw Error("pending nonce exists");const tx=await w.sendTransaction({...b.transaction,gasLimit:gas,nonce:pending});const r=await tx.wait();if(!r||r.status!==1)throw Error("Kyber liquidation failed");return {hash:r.hash,status:r.status,blockNumber:r.blockNumber,gasUsed:r.gasUsed,amountIn:amount};}
async function execute(build:()=>Promise<any>){const b=await build(),w=wallet();if(w.address.toLowerCase()!==OWNER.toLowerCase())throw Error("wallet identity mismatch");const nonce=await provider.getTransactionCount(w.address,"pending");const latest=await provider.getTransactionCount(w.address,"latest");if(nonce!==latest)throw Error("pending nonce exists");const tx=await w.sendTransaction({...b.transaction,nonce});const r=await tx.wait();if(!r||r.status!==1)throw Error("atomic receipt failed");const iface=new ethers.Interface(ABI);let event:any;for(const l of r.logs)try{const x=iface.parseLog(l);if(x?.name==="Opened"||x?.name==="Closed")event={name:x.name,tokenId:x.args.tokenId,token:x.args.token,pool:x.args.pool,usdgIn:x.args.usdgIn,tokenOut:x.args.tokenOut,settlementAmount:x.args.settlementAmount,tokenAmount:x.args.tokenAmount};}catch{}return {...b,receipt:{hash:r.hash,status:r.status,blockNumber:r.blockNumber,gasUsed:r.gasUsed},event};}
async function setup(executeIt:boolean){const usdg=new ethers.Contract(USDG,ERC,executeIt?wallet():provider),npm=new ethers.Contract(C.positionManager,NPM,executeIt?wallet():provider),ex=new ethers.Contract(EXEC,ABI,executeIt?wallet():provider);const calls=[{name:"approve_250_usdg",to:USDG,data:usdg.interface.encodeFunctionData("approve",[EXEC,250000000n])},{name:"npm_setApprovalForAll",to:C.positionManager,data:npm.interface.encodeFunctionData("setApprovalForAll",[EXEC,true])},{name:"unpause",to:EXEC,data:ex.interface.encodeFunctionData("setPaused",[false])}];for(const x of calls)await provider.call({from:OWNER,to:x.to,data:x.data});if(!executeIt)return calls;const out=[];for(const x of calls){const t=await wallet().sendTransaction({to:x.to,data:x.data});out.push({name:x.name,hash:t.hash,status:(await t.wait())?.status});}return out;}
async function main(){const [cmd,a,b,d]=process.argv.slice(2);if(cmd==="status"){const e=new ethers.Contract(EXEC,ABI,provider),u=new ethers.Contract(USDG,ERC,provider),n=new ethers.Contract(C.positionManager,NPM,provider);return json({ok:true,executor:EXEC,owner:await e.owner(),paused:await e.paused(),allowance:await u.allowance(OWNER,EXEC),npmApproved:await n.isApprovedForAll(OWNER,EXEC)});}if(cmd==="build_open")return json({ok:true,result:await open(a!,b!)});if(cmd==="execute_open")return json({ok:true,result:await execute(()=>open(a!,b!))});if(cmd==="build_close")return json({ok:true,result:await close(a!)});if(cmd==="execute_close")return json({ok:true,result:await execute(()=>close(a!))});if(cmd==="execute_liquidation")return json({ok:true,result:await executeLiquidation(a!,b!,d!)});if(cmd==="approve_setup")return json({ok:true,simulated:true,calls:await setup(false)});if(cmd==="unpause")return json({ok:true,simulated:true,call:(await setup(false))[2]});throw Error("commands: status|build_open TOKEN USDG_RAW|execute_open TOKEN USDG_RAW|build_close TOKEN_ID|execute_close TOKEN_ID|approve_setup|unpause");}
main().catch(e=>{console.error(JSON.stringify({ok:false,error:String(e.message||e).slice(0,600)}));process.exit(1)});
